<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.0.2 on 2023-06-18 12:20

from django.db import migrations, models
=======

# Generated by Django 3.0.2 on 2023-06-22 09:45

from django.db import migrations, models
import django.db.models.deletion

>>>>>>> abbc309199e5261d66b9e8cbdca1a0d2f0ddf2b9
=======

# Generated by Django 3.0.2 on 2023-06-22 09:45

from django.db import migrations, models
import django.db.models.deletion

>>>>>>> tik-001


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
=======

            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('data_birth', models.DateField(blank=True, verbose_name='дата рождения')),
                ('data_death', models.DateField(blank=True, verbose_name='дата смерти')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=0, max_length=150, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
>>>>>>> tik-001
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='фото')),
                ('is_published', models.BooleanField(default=False, verbose_name='публикация')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.Author', verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.Category', verbose_name='Категория')),
            ],
<<<<<<< HEAD
=======

            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('data_birth', models.DateField(blank=True, verbose_name='дата рождения')),
                ('data_death', models.DateField(blank=True, verbose_name='дата смерти')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=0, max_length=150, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='фото')),
                ('is_published', models.BooleanField(default=False, verbose_name='публикация')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.Author', verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.Category', verbose_name='Категория')),
            ],
=======
>>>>>>> tik-001
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },

<<<<<<< HEAD
>>>>>>> abbc309199e5261d66b9e8cbdca1a0d2f0ddf2b9
=======
>>>>>>> tik-001
        ),
    ]
